language: scala

scala:
  -  2.11.8

before_install:
  - sudo apt update -y

install:
  - ".checker/scripts/install-jar.sh"

script:
  - ".checker/scripts/run-test.sh"

branches:
  only:
    - feature/ci