version: '2'
services:
  jigg:
    build: .
    ports:
      - 8080:8080
    entrypoint:
      - java
      - -Xms1024M
      - -Xmx1024M
      - -cp
      - "target/*:jar/*"
      - jigg.pipeline.PipelineServer
      - -host
      - 0.0.0.0
    volumes:
      - ./script:/jigg/script
      - ./jar:/jigg/jar
